name: flutter_map_radius_cluster_example
description: Example for Flutter Map Marker cluster

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0-dev.1
  flutter_map_animations: ^0.4.2
  flutter_map_radius_cluster:
    path: ../
  kdbush: ^0.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AccurateMapIcon
      fonts:
        - asset: fonts/AccurateMapIcon.ttf


dependency_overrides:
  flutter_map_animations:
    git:
      url: https://github.com/rorystephenson/flutter_map_animations
      ref: flutter-map-v6
