name: flutter_map_radius_cluster
description: A marker clustering plugin for flutter_map which displays markers in a given radius.
version: 2.1.0

homepage: https://github.com/rorystephenson/flutter_map_radius_cluster

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_map_marker_popup: ^4.0.0
  latlong2: ^0.8.1
  provider: ^6.0.5
  supercluster: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
