name: flutter_map_radius_cluster
description: A marker clustering plugin for flutter_map which displays markers in a given radius.
version: 3.1.0-dev.1

homepage: https://github.com/rorystephenson/flutter_map_radius_cluster

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  flutter_map: ^6.0.0-dev.1
  flutter_map_marker_popup: ^5.3.0-dev.1
  latlong2: ^0.9.0
  supercluster: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

